function [max_size_def] = size_definition(weight, planformarea, payload_frac, parameters, assumptions)

max_size_def = struct( ...
    'score',payload_frac , ...
    'weight', weight.weight, ...
    'planformarea', planformarea, ...
    'weight_payload', weight.weight_payload,...
    'vstall', parameters.vstall, ...
    'vcruise', parameters.vcruise,...
    'radiusturn', parameters.radiusturn,...
    'AR', parameters.AR, ...
    'airfoil', parameters.airfoil, ...
    'powertrain', parameters.powertrain,...
    'weight_airframe', weight.weight_airframe, ...
    'weight_propulsion', weight.weight_propulsion, ...
    'weight_component', weight.weight_components, ...
    'assumptions', assumptions);

end